---
  - name: Remove existing symlink to latest SDK
    file: path={{nrf}}/sdk/{{symlink}} state=absent

#  - name: Set symlink to V8
#    file: src={{nrf51_sdk_8_dest}} dest={{nrf}}/sdk/{{symlink}} state=link

#  - name: Set symlink to V9
#    file: src={{nrf51_sdk_9_dest}} dest={{nrf}}/sdk/{{symlink}} state=link

#  - name: Set symlink to V10
#    file: src={{nrf51_sdk_10_dest}} dest={{nrf}}/sdk/{{symlink}} state=link

  - name: Set symlink to V11
    file: src={{nrf51_sdk_11_dest}} dest={{nrf}}/sdk/{{symlink}} state=link

#  - name: Set symlink to NRF52
#    file: src={{nrf52_sdk_092_dest}} dest={{nrf}}/sdk/{{symlink}} state=link

  - name: Create EHAL latest symlink
    file: src={{nrf}}/sdk/ehal_2015_09_08 dest={{nrf}}/sdk/ehal_latest state=link

  - name: Create EHAL symlink
    file: src={{nrf}}/sdk/arm_cmsis_4_3/CMSIS dest={{nrf}}/sdk/ehal_latest/ARM/CMSIS state=link

  - name: Fix directory mode
    file: path={{item}} recurse=yes mode="u=rwx"
    with_items:
      - "{{nrf}}/sdk/nrf51_sdk_8_0"
      - "{{nrf}}/sdk/nrf51_sdk_9_0"
      - "{{nrf}}/sdk/nrf51_sdk_10_0"
      - "{{nrf}}/sdk/nrf51_sdk_11_0"

  - name: Update fruitymesh project from git
    git: repo=https://github.com/mwaylabs/fruitymesh.git dest={{nrf}}/projects/fruitymesh accept_hostkey=true update=no

  - name: Set ownership of our files
    file: path={{item}} owner={{user}} group={{user}} recurse=yes state=directory
    with_items:
      - "{{nrf}}"

  - name: Remove unnecessary files
    file: path={{item}} state=absent
    with_items:
      - '{{nrf}}/projects/put your project folders here'

  - name: Copy ble_radio_notificatons patched files
    copy: src={{item}} dest={{nrf51_sdk_11_dest}}/components/ble/ble_radio_notification/{{item}} owner={{user}} group={{user}}
    with_items:
      - ble_radio_notification.c
      - ble_radio_notification.h

  - name: Copy app_uart_fifo patched file
    copy: src={{item}} dest={{nrf51_sdk_11_dest}}/components/libraries/uart/{{item}} owner={{user}} group={{user}}
    with_items:
      - app_uart_fifo.c

  - name: Patch makefile error 1 until PR is accepted
    lineinfile: dest="{{nrf}}/projects/fruitymesh/Makefile"
      regexp="^SDK_BASE"
      line="SDK_BASE      := $(HOME)/nrf/sdk/nrf51_sdk_latest"
      state=present

  - name: Patch makefile error 2 until PR is accepted
    lineinfile: dest="{{nrf}}/projects/fruitymesh/Makefile"
      regexp="^EHAL_PATH"
      line="EHAL_PATH     := $(HOME)/nrf/sdk/ehal_latest"
      state=present

  - name: Patch main.cpp to not redefine app_error_handler. Danger! Just a hack
    copy: src={{item}} dest={{nrf}}/projects/fruitymesh/src/{{item}} owner={{user}} group={{user}}
    with_items:
      - Main.cpp

