---
  - name: Install needed packages for Pi development
    apt: pkg={{item}} state=installed
    with_items:
      - rsync
      - cmake
      - lib32z1
      - lib32ncurses5
      - lib32bz2-1.0
      - libc6-i386
      - lib32stdc++6

  - name: Include toolchain in path
    lineinfile: dest={{home}}/.bashrc line='export PATH=$PATH:$HOME/{{pi_project}}/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin' regexp='export PATH=$PATH:$HOME/{{pi_project}}/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin'

  - name: Make directory for pi projects
    file: path=/home/{{user}}/{{pi_project}} owner={{user}} state=directory

  - name: Get tools
    git: repo=https://github.com/{{pi_project}}/tools.git dest=/home/{{user}}/{{pi_project}}/tools accept_hostkey=true

  - name: Make directory for pi dev
    file: path=/home/{{user}}/{{pi_project}}/rootfs owner={{user}} state=directory

  - name: Copy cmake file
    template: src=pi.cmake dest=/home/{{user}}/{{pi_project}}/ owner={{user}} group={{user}}

  - name: Copy hello-world maker
    template: src=hello-world.sh dest=/home/{{user}}/{{pi_project}}/ owner={{user}} group={{user}} mode="u+rwx"

  - name: Set ownership of our files
    file: path={{item}} owner={{user}} group={{user}} recurse=yes state=directory
    with_items:
      - "{{home}}/{{pi_project}}"
